version: '3.7'

services:
  loki:
    image: grafana/loki:2.9.6
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - C:/loki-data:/wal  # Host directory mapped to container directory
      - ./loki-config-new:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml  -config.expand-env=true
    restart: always
    

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    restart: always

volumes:
  grafana-data:
